dist: trusty
sudo: required
language: node_js
node_js:
    - '12'

cache:
    directories:
        - ./node_modules
jobs:
    include:
        - stage: build & publish demo
          script:
              - npm run build:demo
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GH_TOKEN
              local_dir: dist/ag-form-builder-demo
          if: branch = master
        - stage: build & publish lib
          script:
              - npm run build:lib
              - npm run publish:lib
          if: branch = master
